# Generated by Django 3.0.6 on 2020-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200602_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_num',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
