# Generated by Django 3.0.6 on 2020-06-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200609_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='original_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Recipe'),
        ),
    ]
